### ISSUE TITLE
Problem running KCV after computer crash

### ISSUE THREAD

**Issue by handyhandy1981** [gakada/KanColleViewer#18]
Hello, 

I've been using KCV with no problem, but after a sudden power failure yesterday that forced my computer to crash, my KCV has problem starting, here are the error script that appeared every time I tried loading the program:

===========================================================
ERROR, date = 4/13/2016 9:51:50 AM +07:00, sender = Name:KanColleViewer.exe
There are no context policies.
,
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Root element is missing. (C:\Users\username\AppData\Local\grabacr.net\KanColleViewer.exe_Url_teyuqzjgkpg1ldj2143vhncoaptu3x3r\0.0.0.0\user.config) ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Configuration.XmlUtil..ctor(Stream stream, String name, Boolean readToFirstElement, ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- End of inner exception stack trace ---
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at Grabacr07.KanColleViewer.Properties.Settings.get_LocalProxyPort()
   at Grabacr07.KanColleViewer.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Grabacr07.KanColleViewer.App.Main()

Any ideas how to get around this problem? I already tried re-downloading the files from github, deleting everything and all, but it still showing me the same errors.

**Comment by gakada** [comment]
Did you tried to delete `C:\Users\username\AppData\Local\grabacr.net\` directory? (also, `0.0.0.0\user.config` is what is strange, should be `3.8.2.562\user.config`). As far as I know, to uninstall KCV you need to delete:

- `%localappdata%\grabacr.net\` (`%localappdata%\Smooth and Flat\` and `%localappdata%\Smooth_and_Flat\` for Yuubari's fork)
- `%appdata%\gakada\` (`%appdata%\Smooth and Flat\` for Yuubari's and `%appdata%\grabacr.net\` for original KCV)
- KCV directory itself.

So you can try to delete all of this, and then try [r562](https://github.com/gakada/KanColleViewer/releases/tag/v3.8.2r562) (and maybe [r561](https://github.com/gakada/KanColleViewer/releases/tag/v3.8.2r561)), [4.2.4](https://github.com/Grabacr07/KanColleViewer/releases/tag/v4.2.4) (Yuubari's [v4.2.4.0](https://github.com/Yuubari/KanColleViewer/releases/tag/v4.2.4.0)) and see if this problem still occurs (and if it's common, or just this fork's problem).

**Comment by handyhandy1981** [comment]
Everything works again after deleting C:\Users\username\AppData\Local\grabacr.net\

Thank you for the assist.

Strangely enough I only have the error occur while trying to run r562, I can run r561 & Yuubari's for just fine. Thanks again and keep up the good work.
